apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: my-sample-app
    release: prometheus
  name: my-sample-app-svm
  namespace: default
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    port: http-web
    scheme: http
    scrapeTimeout: 30s
  jobLabel: my-sample-app
  selector:
    matchLabels:
            app: my-sample-app
